#!/usr/bin/env bash
# homebrew from https://mirrors.tuna.tsinghua.edu.cn/help/homebrew/

cur_dir=${0:A:h}
# cur_dir=$(wzsh plugin home homebrew)
if ! command -v "brew" >/dev/null 2>&1; then
    install_brew=${cur_dir}/install-brew
    $install_brew
else
    echo "✓ Homebrew Installed in $(command -v brew)"
fi

# 安装 wbrew
original_dir=$(pwd)
cd ${cur_dir}/lib/wbrew

echo "Install ${cur_dir}/lib/wbrew"

GOBIN=${WZSH_BIN} go install .
cd ${original_dir}
