
zdebug "初始化 homebrew 环境"
if [ -d "/usr/local/Homebrew" ]; then
    export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles/bottles #ckbrew
    eval $(/usr/local/Homebrew/bin/brew shellenv) #ckbrew
fi
