#===============================
# Name: wxnacy's Wzsh setting
# Author: wxnacy <wxnacy@gmail.com>
# URL: https://wxnacy.com
# Created: 2022-01-06
# Modified: 2022-01-06
# Description: homebrew 相关命令
#===============================


function binfo() {
    name=$1
    brew info ${name} --json=v2 | bat --theme "Visual Studio Dark+"
}
