#!/bin/zsh
#

cur_dir=${0:A:h}
source $cur_dir/zshenv

if [[ ! -f $ZINIT_ZSH ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$ZINIT_HOME" && command chmod g-rwX "$ZINIT_HOME"
    command git clone --depth=1 https://github.com/zdharma-continuum/zinit "$ZINIT_GIT_HOME" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
else
    zinfo "zinit 脚本已存在 $ZINIT_ZSH"
fi
