# 参考
# https://www.aloxaf.com/2019/11/zplugin_tutorial/
# https://zenlian.github.io/zsh-zinit/
# https://github.com/zdharma-continuum/zinit
. ${WZSH_HOME}/plugins/wzsh-zinit/aliases.zsh

# 加载 zinit
source "$ZINIT_ZSH"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load powerlevel10k theme
zinit ice depth"1" # git clone depth
zinit light romkatv/powerlevel10k
# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
# 停止提示 p10k configure
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true

# 语法高亮
zinit ice lucid wait='0' atinit='zpcompinit'
# https://github.com/zdharma-continuum/fast-syntax-highlighting
zinit light zdharma-continuum/fast-syntax-highlighting
# https://github.com/zsh-users/zsh-syntax-highlighting
# 老版本先不在使用
# zinit light zsh-users/zsh-syntax-highlighting

# 自动建议
# https://github.com/zsh-users/zsh-autosuggestions
zinit ice lucid wait="0" atload='_zsh_autosuggest_start'
zinit light zsh-users/zsh-autosuggestions

# 补全
zinit ice lucid wait='0'
zinit light zsh-users/zsh-completions

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust

# oy-my-zsh
zinit snippet OMZ::lib/key-bindings.zsh
zinit snippet OMZ::lib/completion.zsh
zinit snippet OMZ::lib/history.zsh

if command -v "autojump" >/dev/null 2>&1; then
    zinit ice lucid wait='1'
    zinit snippet OMZ::plugins/autojump
fi
zinit ice lucid wait='1'
zinit snippet OMZ::plugins/git
