#!/usr/bin/env bash
# Author: wxnacy(wxnacy@gmail.com)
# Description:

echo 'The final step is to complete the configuration of Wzsh'
echo 'Run these commands'
echo ''
echo -n -e "\t"
echo 'ln -sf $(pwd)/.wzsh ${HOME}/.zsh'
echo -n -e "\t"
echo 'ln -sf $(pwd)/.wzsh/zshenv ${HOME}/.zshenv'
echo -n -e "\t"
echo 'ln -sf $(pwd)/.wzsh/zprofile ${HOME}/.zprofile'
echo -n -e "\t"
echo 'ln -sf $(pwd)/.wzsh/zshrc ${HOME}/.zshrc'
echo -n -e "\t"
echo 'zsh'

ln -sf $(pwd) ${HOME}/.zsh
ln -sf $(pwd)/zshenv ${HOME}/.zshenv
ln -sf $(pwd)/zprofile ${HOME}/.zprofile
ln -sf $(pwd)/zshrc ${HOME}/.zshrc
zsh
