. ${WZSH_HOME}/plugins/wzsh-direnv/aliases.zsh
. ${WZSH_HOME}/plugins/wzsh-direnv/config/direnvrc

if [[ $(has_command direnv) ]]
then
    zdebug 'Run command: eval "$(direnv hook zsh)"'
    eval "$(direnv hook zsh)"
fi
