default_arg="--icons=always -olMh --git --git-repos-no-status --time-style='+%Y-%m-%d %H:%M'"
alias ll="eza ${default_arg}"
alias la="eza -a ${default_arg}"
alias lh="eza -a --total-size ${default_arg}"
alias lt="eza -a -T -L 3 ${default_arg}"
