#!/bin/zsh

z link /Volumes/ZhiTai/影片 ${OBSIDIAN_HOME}/附件/影片
z link /Volumes/ZhiTai/书籍 ${OBSIDIAN_HOME}/附件/书籍
z link ${HOME}/Projects/obsidian-douban-play-record ${OBSIDIAN_HOME}/.obsidian/plugins/obsidian-douban-play-record
z link ${HOME}/Projects/obsidian-fold-properties ${OBSIDIAN_HOME}/.obsidian/plugins/obsidian-fold-properties
