#===============================
# Name: wxnacy's Wzsh setting
# Author: wxnacy <wxnacy@gmail.com>
# URL: https://wxnacy.com
# Created: 2021-06-11
# Modified: 2021-12-02
# Description: wzsh-git 插件
#===============================

. ${WZSH_HOME}/plugins/wzsh-git/aliases.zsh

source ${WZSH_HOME}/plugins/wzsh-git/forgit.zsh

# 推送
function gpush(){
    proxyon
    bname=`git branch | grep '*' | awk '{print $2}'`
    zinfo '当前分支:' $bname
    gcmit $@
    git pull origin $bname
    git push origin $bname
    proxyoff
}

# 创建并推送 tag
function gptag(){
    git tag ${1}
    proxyon
    git push origin ${1}
    proxyoff
}

# 添加并提交
function gcmit(){
    file=$1
    if [ $file ]
    then
        zinfo '提交文件:' ${file}
        git add $file
    else
        zwarn '无提交文件'
    fi
    # 只匹配开头替换 file 内容
    msg=${@/#$1/}
    # 去掉开头空格
    msg=${msg/# /}
    if [ $msg ]
    then
        zinfo '提交信息:' ${msg}
        git commit -m "$msg"
    fi
}

# 拉取
function gpull(){
    bname=`git branch | grep '*' | awk '{print $2}'`
    zinfo "当前分支名称: ${bname}"
    proxyon
    git pull origin $bname $@
    proxyoff
}

function gsub(){
    # 拉去子模块初始状态
    proxyon
    zinfo '拉取子模块初始化状态'
    git submodule update --init --recursive
    proxyoff
}

function gsubr(){
    # 从远程拉去最新子模块的提交
    proxyon
    zinfo '拉取子模块最新提交'
    git submodule update --recursive --remote
    proxyoff
}

function gsuba(){
    # 添加子模块
    proxyon
    zinfo '添加子模块'
    git submodule add --force $@
    proxyoff
}

# 删除子模块，并提交
function gsubm(){
    local p=$1
    git submodule deinit -f $p
    git rm -f $p
    rm -rf .git/modules/${p}
    git commit -m "feat(gitmodules): Remove git submodule ${p}"
}

# git clone
function glone(){
    proxyon
    params=$(python3 $WZSH_GIT_PY conver_clone_url $@)
    zinfo "解析参数 $params"
    git clone $params
    proxyoff
}

# 配置
function gconf(){
    git config user.name "${WZSH_GIT_NAME}"
    git config user.email "${WZSH_GIT_EMAIL}"
}

# 全局配置
function ggconf(){
    git config --global user.name "${WZSH_GIT_NAME}"
    git config --global user.email "${WZSH_GIT_EMAIL}"
}

# 修改 remove url 到 ssh
function git-set-ssh-url(){
    name="origin"
    url=$(git remote get-url ${name})
    ssh_url=$(python3 $WZSH_GIT_PY conver_clone_url ${url})
    git remote set-url ${name} ${ssh_url}
}

# 增加 .gitlint
function gitlint-config(){
    name=.gitlint
cat > $name <<EOF
[general]
ignore=B6
contrib=CT1
EOF
}
