. ${WZSH_HOME}/plugins/wzsh-mpv/aliases.zsh


# 使用 fzf 列举播放历史，搜索后播放
function ml () {
    p=$(sort -r -n -t ':' -k1,1 ${MPV_HISTORY} | fzf +m)
    after_colon=$(echo "$p" | awk -F: '{print $2}')
    z mpv play $after_colon
}

# 测试窗口
function mt () {
    mpv --input-test --force-window --idle
}
