. ${WZSH_HOME}/plugins/wzsh-yazi/aliases.zsh


# 我们建议使用这个 y shell 包装器，它提供了在退出 Yazi 时更改当前工作目录的能力。
# from https://yazi-rs.github.io/docs/quick-start#shell-wrapper
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}
